portal/groups/urls.py
'''Relative URLs for APPNAME = "groups"'''

from django.conf.urls import url

urlpatterns = [

	url(r'(?P<group_name>[A-Za-z_\-]+)/$','groups.views.group_render',name = 'my_group'),

]

portal/users/models.py
'''----------------------------------------------------------------------------------'''
#Django Related imports.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
'''----------------------------------------------------------------------------------'''

#Database related models.

'''----------------------------------------------------------------------------------'''

#Choices for different fields.


#Model for teacher.
class myuser(AbstractUser):
	SHIFTS = (
		('morning','Morning'),
		('evening','Evening'),
	)
	BRANCH = (
			('cse','Computer Science & Engineering'),
			('ece','Electronics & Communication Engineering'),
			('it','Information Technology'),
			('eee','Electronics & Electrical Engineering'),
		)
	GENDER_CHOICES = (
			(None,'Gender'),
			('M','Male'),
			('F','Female'),
			('T','Transgender')
		)
	gender=models.CharField(_('Gender') , max_length=1 , choices=GENDER_CHOICES , blank=True)
	avatar = models.ImageField(_('Avatar'),upload_to = 'avatars/',blank=True)	
	department = models.CharField(max_length = 50 , choices = BRANCH , null = True)
	shift = models.CharField(max_length = 10 ,choices = SHIFTS , null = True)
	contact_number = models.CharField(max_length = 10 , null = True)
	is_teacher = models.BooleanField('Are you a teacher?' , default=False)

	def __str__(self):
		return self.username
	def get_avatar(self):
		if self.avatar:

			return '<img height="128px" width="128px" class="responsive-image circle" src="/media/%s" alt="UserImage">' % self.avatar
		else: 
			return '<img height="128px" width="128px" class="responsive-image circle" src="/media/avatars/default.png" alt="UserImage">'		

class teacher(models.Model):
	user = models.OneToOneField(myuser , related_name = 'teacher_parent')
	DESIGNATION = (
		('asst. prof','Asst. Professor'),
		('prof','Professor'),
		('reader','Reader'),
	)
	teacher_id = models.CharField(max_length = 12)
	designation = models.CharField(max_length = 20 , choices = DESIGNATION)
	is_hod = models.BooleanField(default = False)
	def __str__(self):
		return self.user.username


class student(models.Model):
	user = models.OneToOneField(myuser , related_name = 'student_parent')
	enrollment_no = models.CharField(max_length = 12)
	#tech_choice = models.CharField(max_length = 50)
	
	def __str__(self):
		return self.user.username

portal/users/views.py
'''--------------------------------------------------------------------------------------'''

#Django Related imports
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.template import RequestContext

'''--------------------------------------------------------------------------------------'''
#Database related models.
from .models import *
from users.models import *

'''----------------------------------------------------------------------------------'''


# Create your views here.

'''View For About us page'''
def about_us(request):
	return render(request , 'about_us/about_us.html')

'''View For Home page'''
def home(request):
	return render(request , 'home/home.html')

'''View For Index page'''
def index(request):
	if request.user.is_authenticated():
		return redirect('/dashboard')
	else:
		return render(request , 'index.html')

"""View for MyProfile Page"""

def my_profile(request,username):
	print(username)
	user=myuser.objects.get(username=username)
	context = {
		'user' : user,
	}
	return render(request , 'users/myprofile.html',context)

portal/templates/users/myprofile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title%} 
	My Profile
{% endblock title %}

{% block cssfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/myprofile.css' %}">
{% endblock cssfiles %}

{% block nav%}
	<li><a href="{% url 'profile' user %}">My Profile</a></li>
	<li><a href="{% url 'logout' %}">Logout</a></li>
{% endblock nav%}

{%block content %}
  <div id="usercard" class="container">
    <div class="row center">
      
        <div class="card z-depth-2">
          <div class="card-content white">
            {{user.get_avatar|safe}}
            <div class="card-title black-text"><b>{{user.get_full_name}}</b></div>
            <div class="row">
              <div class="col s12 m12 l6">
                <div class="section">User Details</div>
                <div class="divider"></div>
                <div class="section left-align">
                  <ul class="collection">
                    <li class="collection-item"><b>Gender</b> <em class="right">{{user.get_gender_display}}</em></li>
                    <li class="collection-item"><b>Department</b> <em class="right">{{user.get_department_display}}</em></li>
                    <li class="collection-item"><b>Shift</b> <em class="right">{{user.get_shift_display}}</em></li>
                  </ul>
                </div>
              </div>
              <div class="col s12 m12 l6">
                <div class="section">Contact Details</div>
                <div class="divider"></div>
                <div class="section left-align">
                  <ul class="collection">
                    <li class="collection-item"><b>Email</b> <em class="right">{{user.email}}</em></li>
                    <li class="collection-item"><b>Mobile Number</b> <em class="right">{{user.contact_number}}</em></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      
    </div>
  </div>
{%endblock%}