portal/groups/urls.py
'''Relative URLs for APPNAME = "groups"'''

from django.conf.urls import url

urlpatterns = [

	url(r'(?P<group_name>[A-Za-z_\-]+)/$','groups.views.group_render',name = 'my_group'),

]

portal/groups/models.py
'''---------------------------------------------------------------------------------'''

#Django Related Imports
from django.db import models

'''---------------------------------------------------------------------------------'''

#Database model related imports.
from users.models import teacher , student
from queries.models import query
from posts.models import post
'''---------------------------------------------------------------------------------'''

#Class for groups.
class group(models.Model):

	#choices for parent groups
	TYPES_OF_GROUP= (
		('web_dev' , 'Web Development'),
		('mob_dev' , 'Mobile Application Development'), 
		('competitive_prog' , 'Competitive Programming'),
		('career_planning' , 'Higher Studies'),
		('ui_ux' , 'UI/UX Design')
	)

	name = models.CharField(max_length = 500)
	description = models.TextField(blank = True)
	members = models.ManyToManyField(student , symmetrical = False , related_name = 'group_members' , blank = True)
	mentors = models.ManyToManyField(student , symmetrical = False , related_name = 'group_mentors' , blank = True)
	admin = models.ManyToManyField(teacher , symmetrical = False , related_name = 'group_admins' , blank = True)
	posts = models.ManyToManyField(post , symmetrical = False , related_name = 'group_posts' , blank = True)
	doubts = models.ManyToManyField(query , symmetrical = False , related_name = 'group_doubts' , blank = True)
	display_pic = models.ImageField(upload_to = 'group_pics/' , blank = True) 
	type_of_group =  models.CharField(max_length = 30 , choices = TYPES_OF_GROUP)
	slug = models.SlugField(max_length = 100 , blank = True)


	def __str__(self):
		return self.name

portal/groups/views.py
'''----------------------------------------------------------------------------------'''

#Django Related imports.
from django.shortcuts import render
from django.http import HttpResponse
from django.db import models
from django.contrib.auth.decorators import login_required
from django.core import serializers
'''----------------------------------------------------------------------------------'''

#Database related models.
from users.models import myuser
from .models import group
from posts.models import post
from queries.models import query

'''----------------------------------------------------------------------------------'''

#Form imports.
from posts.forms import group_post
from queries.forms import query_form

'''----------------------------------------------------------------------------------'''

# Create your views here.
@login_required()
def group_render(request , group_name):
	a,b=0,1
	group_name = group.objects.get(slug = group_name)
	resources = group_name.posts.order_by('created_timestamp').reverse()
	doubts = group_name.doubts.order_by('created_timestamp').reverse()
	if request.method == 'GET':
		form2 = query_form()
		if group_name.mentors.filter(user = request.user).count() != 0:
			form1 = group_post()
			a=1
			context = {'group' : group_name , 'form1' : form1 , 'form2' : form2 ,'a':a , 'b':b , 'resources' : resources , 'doubts' : doubts}
		else :
			context = {'group' : group_name , 'a':a , 'b':b , 'resources' : resources , 'form2' : form2 , 'doubts' : doubts}
		return render(request , 'groups/group.html' , context)
	elif request.method == 'POST':
			title = request.POST['title']
			content = request.POST['content']
			post_now = post.objects.create(title= title , content = content , posting_user  = request.user)
			group_name.posts.add(post_now)
			json_response = serializers.serialize('json', [ post_now ])
			return HttpResponse(json_response)

#Function for posting a data. Return json response for the latest doubt.
@login_required()
def query_post(request , group_name):
	if request.method == 'POST':
		content = request.POST['content']
		query_now = query.objects.create(content = content , query_poster  = request.user)
		group_name = group.objects.get(slug = group_name)
		group_name.doubts.add(query_now)
		json_response = serializers.serialize('json', [ query_now ])
		return HttpResponse(json_response)
	else:
		return HttpResponse("Request Denied.")

portal/templates/groups/group.html
{% extends 'base.html' %}
{% load material_form %}
{% load staticfiles %}
{% block title %}
    {{ group.name }}
{% endblock title %}
{% block nav%}
	<li><a href="{% url 'profile' %}">My Profile</a></li>
    <li><a href="{% url 'logout' %}">Logout</a></li>
{% endblock nav%}
{% block mob-nav %}
	<li><a href="/profile">My Profile</a></li>
    <li><a href="/loginauth/logout">Logout</a></li>
{% endblock mob-nav %}
{% block cssfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'groups/css/group.css' %}">
{% endblock cssfiles %}

{% block content %}
	<div class="background-grey">
    <img class="group-image" src="{{MEDIA_URL}}{{group.display_pic}}"></div>
    	<div class="col s12 m12 l12 background-white">
		    <ul class="tabs">
				<li class="tab col s3"><a href="#About">About This Group</a></li>
		        <li class="tab col s3"><a class="active" href="#Resources">Resources</a></li>
		        <li class="tab col s3"><a href="#Doubts">Doubts</a></li>
		    </ul>
    	</div>
    	
    	<div id="About" class="container col s12">
    		<table class="bordered centered z-depth-1 background-white text-align-center">	
    			<tr>
    				<td>Name of Group :</td>
    				<td>{{ group.name }}</td>
    			</tr>
    			<tr>
    				<td>Type :</td>
    				<td>{{ group.get_type_of_group_display }}</td>
    			</tr>
    		</table>
    		<ul class="collapsible text-align-center" data-collapsible="accordian">
    			<li>
				   <div class="collapsible-header">About this Group</div>
				   <div class="collapsible-body"><p>{{group.description}}</p></div>
				</li>
				<li>
				   <div class="collapsible-header">Members</div>
				   <div class="collapsible-body">
				   		{% for g in group.members.all %}
								<div>{{ g.user.first_name }} {{ g.user.last_name }}</div>
						{% endfor %}
				   </div>
				</li>
				<li>
				   <div class="collapsible-header">Mentors</div>
				   <div class="collapsible-body">
				   		{% for g in group.mentors.all %}
								<div>{{ g.user.first_name }} {{ g.user.last_name }}</div>
						{% endfor %}
				   </div>
				</li>
			</ul>
    	</div>
    	<div id="Resources" class="col s12">
    		<div class="container">
    			<p class="flow-text">Group Posts</p>
    			<input type="hidden" value="{{group.slug}}" id="slug">
    			{% if a == b %}
    				<div class="z-depth-1 post background-white">
    				<div class="row">
    					<div class="col s2 offset-s5 image-url image-form" style="background-image:url({{MEDIA_URL}}{{request.user.avatar}});"></div>
    				</div>
    					<blockquote class="flow-text">Post a Resource!</blockquote>
    				<form method = "POST" id="resource_form">
    					{% csrf_token %}
    					{% form form=form1 %}
    					{% endform %}
    					<input type="submit" class="btn waves-effect" value="Post it!">
    				</form>
    			</div>
    			{% endif %}
    			<div id = "post_container">
    			{% for g in resources %}
    				<div class="z-depth-1 post background-white">
    					<div class = "image-url image-post" style="background-image:url({{MEDIA_URL}}{{request.user.avatar}});"></div>
    					<h5><strong>{{ g.title }}</strong></h5>
    					<p>{{ g.content|urlize|linebreaksbr }}</p>
                        <p class = "teal-text right">{{ g.created_timestamp }}</p>
    					<button class="btn-floating waves-effect">+</button>
    				</div>
    			{% endfor %}
                </div>
    		</div>
    	</div>
    	<div id="Doubts" class="col s12">
    		<div class="container">
    			<p class="flow-text">Doubts and Queries</p>
    			<div class="z-depth-1 post background-white">
    				<div class="row">
    					<div class="col s2 offset-s5 image-url image-form" style="background-image:url({{MEDIA_URL}}{{request.user.avatar}});"></div>
    				</div>
    				<blockquote class="flow-text">Post a Doubt!</blockquote>
    				<form method = "POST" id="doubt_form">
        				{% csrf_token %}
        				{% form form=form2 %}
        				{% endform %}
    				<input type="submit" class="btn waves-effect" value="Post it!">
    			</form>
    			</div>
                <div id="doubt_container">
    			{% for g in doubts %}
    				<div class="z-depth-1 post background white">
    					<div class = "image-url image-post" style="background-image:url({{MEDIA_URL}}{{request.user.avatar}});"></div>
    					<p>{{ g.content|urlize|linebreaksbr }}</p>
    				</div>
    			{% endfor %}
                </div>
    		</div>
    	</div>
	</div>	
{% endblock content %}
{% block jsfiles %}
	{{block.super}}
	<script type="text/javascript" src="{% static 'groups/js/group_page.js' %}"></script>
{% endblock jsfiles %}